spring.application.name=earnings-app

# Po??czeniem bazy danych zarz?dza Hibernate.
spring.datasource.url=${earnings_db_url}
spring.datasource.username=${earnings_db_username}
spring.datasource.password=${earnings_db_password}

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update